In [1]:
import numpy as np

### Создание массивов

In [2]:
# Произвольный одномерный массив
arr1 = np.array([1, 2, 3, 4])
arr1

array([1, 2, 3, 4])

In [3]:
# Произвольный двухмерный массив
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# Одномерный массив нулей из 5 элементов
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
# Одномерный массив единиц
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
# Двумерный массив единиц или нулей
np.zeros([5, 2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
# Пустой массив
np.empty(5)

array([1., 1., 1., 1., 1.])

In [8]:
# Последовательность чисел
np.arange(5)

array([0, 1, 2, 3, 4])

In [9]:
# Линейное разделение отрезка на точки (отрезок от 0 до 10 5 точек)
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### Атрибуты массива

In [10]:
arr_attrs = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Измерения массива {arr_attrs.ndim}")
print(f"Строки и столбцы {arr_attrs.shape}")
print(f"Элементы массива {arr_attrs.size}")
print(f"Тип данных {arr_attrs.dtype}")

Измерения массива 2
Строки и столбцы (3, 3)
Элементы массива 9
Тип данных int64


### Срезы

Общий формат для 2D массива:
```
array[строки, столбцы]
```
* : — означает «все элементы» по соответствующему измерению
* число — конкретный индекс
* a:b — срез с a до b (не включая b)
* Можно комбинировать: array[1:, :2] — со 2-й строки, первые два столбца

In [11]:
slices_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
slices_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
# Вызов строки
slices_array[0]

array([1, 2, 3])

In [13]:
# Вызов столбца
slices_array[:, 2]

array([3, 6, 9])

In [14]:
# Вызов элемента
slices_array[0, 1]

np.int64(2)

In [15]:
# Изменение элемента
slices_array[0, 1] = 10
slices_array

array([[ 1, 10,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [16]:
# До 3 строки
slices_array[:2]

array([[ 1, 10,  3],
       [ 4,  5,  6]])

In [17]:
# До 3 строки 3 столбец
slices_array[:2, 2]

array([3, 6])

In [18]:
# начиная со второй строки и со второго столбца  # noqa: RUF003

slices_array[1:, 1:]

array([[5, 6],
       [8, 9]])

### Арифметические операции с одномерными массивами

In [19]:
arith1 = np.arange(5)
arith2 = np.arange(10, 15)
print(arith1, arith2)

[0 1 2 3 4] [10 11 12 13 14]


In [20]:
# сложение элементов
arith1 + arith2

array([10, 12, 14, 16, 18])

In [21]:
# вычитание элементов
arith1 - arith2

array([-10, -10, -10, -10, -10])

In [22]:
# умножение элементов
arith1 * arith2

array([ 0, 11, 24, 39, 56])

In [23]:
# деление элементов
arith1 / arith2

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429])

In [24]:
# Возведение в степень каждого элемента
arith1**2

array([ 0,  1,  4,  9, 16])

In [25]:
# Логические операции с каждым из элементов  # noqa: RUF003
arith1 < 3  # noqa: PLR2004

array([ True,  True,  True, False, False])

### Арифметические операции с двумерными массивами

In [26]:
arith1_2d = np.array([[1, 1], [0, 1]])
arith2_2d = np.array([[2, 0], [3, 4]])
print(arith1_2d)
print(arith2_2d)

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]


In [27]:
arith1_2d + arith2_2d

array([[3, 1],
       [3, 5]])

In [28]:
arith1_2d * arith2_2d

array([[2, 0],
       [0, 4]])

In [29]:
# умножение матриц
arith1_2d @ arith2_2d

array([[5, 4],
       [3, 4]])

In [30]:
# Транспонирование матрицы
arith1_2d.T

array([[1, 0],
       [1, 1]])

### Методы агрегирования 

In [31]:
data = np.array([[1, 2], [5, 3], [4, 6]])

In [32]:
data.min()

np.int64(1)

In [33]:
data.max()

np.int64(6)

In [34]:
data.sum()

np.int64(21)

In [35]:
data.mean()

np.float64(3.5)

In [36]:
# Произведение всех элементов
data.prod()

np.int64(720)

In [37]:
# Дисперсия
data.var()

np.float64(2.9166666666666665)

In [38]:
# Стандартное отклонение
data.std()

np.float64(1.707825127659933)

### Создание массива случайных чисел

In [39]:
from numpy.random import default_rng

In [40]:
default_rng(42).random(5)

array([0.77395605, 0.43887844, 0.85859792, 0.69736803, 0.09417735])

In [41]:
default_rng(42).random([2, 3])

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235]])

### Изменение формы массива

In [42]:
shapes_arr = np.floor(10 * default_rng(42).random((3, 4)))
shapes_arr

array([[7., 4., 8., 6.],
       [0., 9., 7., 7.],
       [1., 4., 3., 9.]])

In [43]:
shapes_arr.ravel()

array([7., 4., 8., 6., 0., 9., 7., 7., 1., 4., 3., 9.])

In [44]:
shapes_arr.reshape(2, 6)

array([[7., 4., 8., 6., 0., 9.],
       [7., 7., 1., 4., 3., 9.]])

In [45]:
shapes_arr.reshape(2, 3, 2)

array([[[7., 4.],
        [8., 6.],
        [0., 9.]],

       [[7., 7.],
        [1., 4.],
        [3., 9.]]])

### Объединение массивов

In [46]:
concat_arr = np.floor(10 * default_rng(42).random((3, 4)))
concat_arr2 = np.floor(10 * default_rng(52).random((3, 4)))
print(concat_arr)
print(concat_arr2)

[[7. 4. 8. 6.]
 [0. 9. 7. 7.]
 [1. 4. 3. 9.]]
[[6. 5. 5. 0.]
 [5. 9. 3. 0.]
 [2. 9. 8. 4.]]


In [47]:
# По строкам
np.vstack((concat_arr, concat_arr2))

array([[7., 4., 8., 6.],
       [0., 9., 7., 7.],
       [1., 4., 3., 9.],
       [6., 5., 5., 0.],
       [5., 9., 3., 0.],
       [2., 9., 8., 4.]])

In [48]:
# По столбцам
np.hstack((concat_arr, concat_arr2))

array([[7., 4., 8., 6., 6., 5., 5., 0.],
       [0., 9., 7., 7., 5., 9., 3., 0.],
       [1., 4., 3., 9., 2., 9., 8., 4.]])

### Копирование массивов

In [49]:
mem_arr = np.floor(10 * default_rng(52).random((3, 5)))
mem_arr

array([[6., 5., 5., 0., 5.],
       [9., 3., 0., 2., 9.],
       [8., 4., 1., 0., 9.]])

In [50]:
# Переменные ссылаются на 1 и тот же объект
mem_arr_ptr = mem_arr
print(id(mem_arr), id(mem_arr_ptr), id(mem_arr_ptr) == id(mem_arr))

1877650359472 1877650359472 True


In [51]:
# Также есть новая переменная представление объекта, которое также будет изменять сам объект
mem_arr_view = mem_arr.view()
print(id(mem_arr), id(mem_arr_view), id(mem_arr_view) == id(mem_arr))

mem_arr_view[1, 1] = 10
print(mem_arr[1, 1] == mem_arr_view[1, 1])

1877650359472 1877650359376 False
True


In [52]:
# Есть копия, только копия будет изменяться
mem_arr_copy = mem_arr.copy()
print(id(mem_arr), id(mem_arr_copy), id(mem_arr_copy) == id(mem_arr))

mem_arr_copy[1, 1] = 30
print(mem_arr[1, 1] == mem_arr_copy[1, 1])

1877650359472 1877650359952 False
False
